### ISSUE TITLE
Native bindings with node-postgres

### ISSUE THREAD

**Issue by martinell** [jugglingdb/postgres-adapter#11]
Hello,

I tried to run my project with the native bindings and it was crashing. I saw that the supported version of node-postgres is 0.7.2. I tested it updated to the version 0.11.2 and everything worked for me. Is it possible to update the version or there is a reason to stick to the current one? It would be great, also, if the module offers some configuration options to switch from the javascript bindings to the native ones.

Thanks

**Comment by rex** [comment]
I gotta say, man. What the heck. Why is this adapter not using the **non**-native library? Possibly with the option to use the native bindings? I tried installing this adapter and in order for it to work I had to:

1) Gain root access to the machine
2) Install the development headers for Postgres (`postgresql-devel`)
3) Update my `$PATH` to point to the new development binaries
4) Confirm that `pg_config` was in my path

Seriously? The `pg` library is a 100% JS-only library with an *optional* set of native bindings. That this package **explicitly disallows** installation of the non-native version is beyond my ability to comprehend. 

Opinionated much?
