### ISSUE TITLE
Is this still in development?

### ISSUE THREAD

**Issue by RichardSimko** [jugglingdb/postgres-adapter#54]
Title says it all. I saw that jugglingdb recently came back to life, does that apply to the adapters as well?

**Comment by 1602** [comment]
Short answer: yes, it is.

Longer answer: I've stated rewriting of sqlite and mysql adapters, postgresql adapter will be updated too, as soon as I'm happy with mysql adapter in production (I plan to release mysql adapter this week, but who knows what will came up). So, expect major release within one month timeframe.

**Comment by RichardSimko** [comment]
Cool, sounds good to me!
